language: node_js
node_js:
 - "10"

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
 - export PATH=$HOME/.yarn/bin:$PATH

cache:
 yarn: true

script:
  - yarn lint
  - yarn test:ci
  - yarn build

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
